# Generated by Django 4.2.1 on 2023-05-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
